name: End-to-end tests

on:
  pull_request:
    branches:
      - QA
jobs:
  cypress-run:
    name: run cypress
    runs-on: ubuntu-18.04
    steps:
      - name: Cypress.io
        uses: cypress-io/github-action@v1.14.0
        with:
          browser: chrome
          record: "true"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
