name: with server
on:
  pull_request:
    branches:
      - QA
jobs:
  cypress-run:
    name: run cypress
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: GitHub Action for Yarn + Cypress
        uses: KingScooty/actions-yarn-cy@1.0.0
      - name: Cypress run
        uses: cypress-io/github-action@v1.14.0
        with:
          start: npm run start
